apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: aws-console-view
subjects:
- kind: User
  name: aws-viewer
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: view-aws
  apiGroup: rbac.authorization.k8s.io