# DEPLOYMENT

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeapp-deployment
  labels:
    app: nodeapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nodeapp
  template:
    metadata:
      labels:
        app: nodeapp
    spec:
      containers:
      - name: nodeapp
        image: 969361958776.dkr.ecr.us-east-1.amazonaws.com/101-docker-images
        ports:
          - containerPort: 8081
      imagePullSecrets:
          - name: regcred
      tolerations:
      - key: special
        operator: "Equal"
        value: "true"
        effect: NoSchedule


---
# SERVICE

apiVersion: v1
kind: Service
metadata:
  name: nodeapp
  namespace: demo
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8081
  type: LoadBalancer
  selector:
    app: nodeapp

---
# INGRESS

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nodeapp-service
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nodeapp
            port:
              number: 80


