# redis StatefulSet
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-server
  namespace: demo
spec:
  serviceName: "redis-server"
  replicas: 1
  selector:
    matchLabels:
      application: redis-server
  template:
    metadata:
      labels:
        application: redis-server
    spec:
      containers:
      - name: redis-server
        image: redis:6.2.6-alpine
        command:
          - redis-server
          - "/redis-master/redis.conf"
        ports:
        - name: redis-server
          containerPort: 6379
        volumeMounts:
        - mountPath: "/var/lib/data"
          name: redis-data
        - mountPath: /redis-master
          name: config
        resources:
          limits:
            cpu: 200m
            memory: 200Mi
      volumes:
        - name: redis-data
          persistentVolumeClaim:
            claimName: redis-data

        - name: config
          configMap:
            name: example-redis-config
            items:
            - key: redis-config
              path: redis.conf
    
---
# ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: example-redis-config
  namespace: demo
data:
  redis-config: |
    dir /var/lib/data
    appendonly yes
    protected-mode no


---
# Persistent volume claim
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-data
  namespace: demo
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi


---
# REDIS SERVICE
apiVersion: v1
kind: Service
metadata:
  name: redis-server
  namespace: demo
  labels:
    application: redis-server
spec:
  clusterIP: None
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    application: redis-server